version: '3'
services:
  myapp:
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - "mongodb"
    #command: ["./wait-for-it.sh", "mongodb:27017", "node", "index.js"]
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest
    container_name: mongo1
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  mongodb1:
    image: mongo:latest
    container_name: mongo2
    volumes:
      - ./data/db:/data/db
    ports:
      - 28018:28018

